
IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = N'dbo' AND TABLE_NAME = N'Entreprise')
BEGIN
CREATE TABLE [dbo].[Entreprise]
(
	[Id] INT NOT NULL PRIMARY KEY, 
    [Libelle] NCHAR(10) NULL
)
END